language: go

os:
  - linux
  - osx

script:
  - go generate
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./tests

after_success:
  - test $TRAVIS_OS_NAME = "linux" && bash <(curl -s https://codecov.io/bash)
