// Generated by embed. DO NOT EDIT.

package tests

import (
	"bytes"
	"io"
)

func EmptyReader() io.Reader {
	return bytes.NewReader(nil)
}

func EmptyReadAll() []byte {
	return nil
}

var cEmpty = ``
