// Generated by embed. DO NOT EDIT.

package tests

import (
	"bytes"
	"encoding/base64"
	"io"
	"io/ioutil"

	"github.com/golang/snappy"
)

func Reader() io.Reader {
	z, err := base64.StdEncoding.DecodeString(c)
	if err != nil {
		panic(err)
	}
	r, err := snappy.Decode(nil, z)
	if err != nil {
		panic(err)
	}
	return bytes.NewReader(r)
}

func ReadAll() []byte {
	data, err := ioutil.ReadAll(Reader())
	if err != nil {
		panic(err)
	}
	return data
}

var c = `2AHobW9kdWxlIGdpdGh1Yi5jb20vbmlrYW5kZm9yL2VtYmVkCgpnbyAxLjEzCgpyZXF1aXJlICgKCWdpdGgNMExnb2xhbmcvc25hcHB5IHYwLjAuMTIhABlRCGNsaQkheDAtMjAxOTEyMDkyMjEyMzctYWQ2Yzk3ZjVhZmFjCgkdXiRwa2cvZXJyb3JzAToAODpbAGRzdHJldGNoci90ZXN0aWZ5IHYxLjMuMAopCg==`
