// Generated by embed. DO NOT EDIT.

package tests

import (
	"bytes"
	"encoding/base64"
	"io"
	"io/ioutil"

	"github.com/golang/snappy"
)

func Reader() io.Reader {
	z, err := base64.StdEncoding.DecodeString(c)
	if err != nil {
		panic(err)
	}
	r, err := snappy.Decode(nil, z)
	if err != nil {
		panic(err)
	}
	return bytes.NewReader(r)
}

func ReadAll() []byte {
	data, err := ioutil.ReadAll(Reader())
	if err != nil {
		panic(err)
	}
	return data
}

var c = `xALgbW9kdWxlIGdpdGh1Yi5jb20vbmlrYW5kZm9yL2VtYmVkCgpnbyAxLjEzCgpyZXF1aXJlICgKCWdpFTBMZ29sYW5nL3NuYXBweSB2MC4wLjEyIQAZUQhjbGkJIXgwLTIwMTkxMjA5MjIxMjM3LWFkNmM5N2Y1YWZhYwoJHV4ZPQxqc29uNj4AgDI2MTgxODM4LWFjYzVmYzI0NzMwZiAvLyBpbmRpcmVjdFpKAAx0bG9nAUoIMy4wMiIAJHBrZy9lcnJvcnMBHgA4OscAZHN0cmV0Y2hyL3Rlc3RpZnkgdjEuMy4wCikK`
