version: 2
jobs:
  go1.13: &base
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/wd
    steps:
      - run: go version

      - checkout

      - run: go generate
      - run: go test -v -race ./...
      - run: ./is_gofmt.sh

  go1.12:
    <<: *base
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE=on

workflows:
  version: 2
  build:
    jobs:
      - go1.12
      - go1.13
